version: '3.7'

services:
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./tsconfig.json:/home/node/app/tsconfig.json
      - ./secrets:/home/node/app/secrets
    env_file:
      - .env
    container_name: ts-node-docker
    environment:
      - DATABASE_HOST=pg
      - DATABASE_USER=commons
      - DATABASE_NAME=commons
      - DATABASE_PASSWORD=commons
      - DATABASE_PORT=5432

    ports:
      - '4000:4000'
      - '4001:443'
    depends_on:
      - 'pg'
    command: yarn run dev-docker
  pg:
    env_file:
      - database.env
    image: 'postgis/postgis'
    container_name: 'postgres'
    ports:
      - '5433:5432'
    volumes:
      - ./pg/db_data:/var/lib/postgresql/data
