version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.15.3
  aws-ecs: circleci/aws-ecs@2.0.0

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: '${AWS_RESOURCE_NAME_PREFIX}'
          tag: '${CIRCLE_SHA1}'
          filters:
            branches:
              only:
                - main
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          family: '${AWS_RESOURCE_NAME_PREFIX}-service'
          cluster-name: '${AWS_RESOURCE_NAME_PREFIX}-cluster'
          container-image-name-updates: 'container=${AWS_RESOURCE_NAME_PREFIX}-service,image-and-tag=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${AWS_RESOURCE_NAME_PREFIX}:${CIRCLE_SHA1}'
          verify-revision-is-deployed: true
          container-env-var-updates: 'container=${AWS_RESOURCE_NAME_PREFIX}-service,name=FIREBASE_KEY,value=${FIREBASE_KEY},container=${AWS_RESOURCE_NAME_PREFIX}-service,name=DATABASE_HOST,value=${DATABASE_HOST}'
          filters:
            branches:
              only:
                - main
